language: cpp
dist: bionic
matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - libssl-dev
        - libcrypto++-dev
    env: ENV_CXX=g++-7 ENV_CC=gcc-7
before_script:
- wget https://github.com/sbx320/premake5-travis/blob/master/premake5?raw=true -O
  ./premake5 && chmod +x ./premake5 && ./premake5 gmake && cd Build
script:
- make -j 3 CXX=$ENV_CXX CC=$ENV_CC config=release_x64
- cd ..
- mv Bin/Release/libml_jwt.so Bin/Release/ml_jwt.so

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ReOy6mA5VqtgDEd+f4tQtNk+3to5bn33mP+AFBHoljcz1JgQ7fCRe4raIGJFPrGxWET37P1vMMIrUc1K0rfmdULELj5VQ0NfmkSiIfFdw+HdQKA5PNVKf1t4zB6PA7nNO+c2N9U812AVqmFK9FJe4gn4W1Tf08zWY0aXD4EL45NEuS382em5ZT2KqWiTeAa1uMxYh8Ro0Ub5HRwX2QxlVromqtmay6h4vckdb+mXdXqOZol72ERe8BT1Oohi/JbCzZLp8kxfarFelaNqZRqdtSdXB90aWMmc4KH2GYKUiv3hic5ZbGxbdOctcaZAIg5KCpQzlnSQ4zrgbU/PxxxDndAEVxfWYSbqa9FtQHccgzBZBvzQn9t1dyI24lygsCk7F5H3Mkspl2BdiBR4XdGBuNaHAh+3xVNplEdfYa/hNeRncDTaW25HADzgUIOQ1eTVYL1eh2JM82KfHMYwGJsg0ZbJTLV7X/CZvzYYWJ9vV5DaIvJi1m2qsSmpbWnGfR5KRSRGYSKNpJlcbpRuIYbAHDwj8unN3wTESGrFX+M93g4Pu+dwV/DwqXv5DUl4Vamo1CaJ0Ly0IGoqP8wacCVseR1fyKGlTsgOfbRPTHfUxBOdlQjYLe44Mav9TLcWveGsNzRoYjgpCe5D3Yh/KTP6YFMzmm4lH7XfrpecEoeFHH8=
  file: Bin/Release/ml_jwt.so
  on:
    repo: eXo-OpenSource/ml_jwt
    tags: true
