version: ci-{build}
os: Visual Studio 2017

configuration:
  - Release

before_build:
  - premake5 vs2017

clone_depth: 1

platform:
  - Win32
  - x64

build:
  parallel: true
  project: Build/PathFind.sln

after_build:
  - ps: |
      if($env:PLATFORM -eq 'x64') {
        $env:NAME = 'ml_pathfind_x64.dll'
      } else {
        $env:NAME = 'ml_pathfind_x86.dll'
      }
      mv Bin/Release/ml_pathfind.dll Bin/Release/$env:NAME
  
artifacts:
  - path: Bin/Release/$(NAME)
    name: "ml_pathfind"

deploy:
  description: 'Pathfind module release'
  provider: GitHub
  auth_token:
    secure: gUShV8myZZHnM6U/HmGkJmtKslpUMglLZoeMPTyMbwNBNskDk0wQ/1HRMoYakQ7A
  artifact: "ml_pathfind"
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
