version: ci-{build}
os: Visual Studio 2019

configuration:
  - Release

before_build:
  - premake5 vs2019

clone_depth: 1

platform:
  - Win32
  - x64

build:
  parallel: true
  project: Build/JWT.sln

after_build:
  - ps: |
      if($env:PLATFORM -eq 'x64') {
        $env:NAME = 'ml_jwt_x64.dll'
      } else {
        $env:NAME = 'ml_jwt_x86.dll'
      }
      mv Bin/Release/ml_jwt.dll Bin/Release/$env:NAME
  
artifacts:
  - path: Bin/Release/$(NAME)
    name: "ml_jwt"

# deploy:
#   description: 'JWT module release'
#   provider: GitHub
#   auth_token:
#     secure: gUShV8myZZHnM6U/HmGkJmtKslpUMglLZoeMPTyMbwNBNskDk0wQ/1HRMoYakQ7A
#   artifact: "ml_jwt"
#   draft: false
#   prerelease: false
#   on:
#     appveyor_repo_tag: true
