jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'

  strategy:
    maxParallel: 2
    matrix:
      Win32:
        platform: 'win32'
      x64:
        platform: 'x64'
  variables:
    solution: 'Build/JWT.sln'
    buildConfiguration: 'Release'
  steps:
  - script: utils\premake5 vs2019
    displayName: 'Create Visual Studio 2019 Solution'
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      configuration: '$(buildConfiguration)'
      platform: '$(platform)'
