jobs:
- job: windows
  pool:
    vmImage: 'windows-2019'

  strategy:
    maxParrallel: 2
    matrix:
      win32Job:
        platform: 'x86'
      win64Job:
        platform: 'x64'
  variables:
    solution: 'Build/JWT.sln'
    buildConfiguration: 'Release'
  steps:
  - script: utils\premake5 vs2019
    displayName: 'Create Visual Studio 2019 Solution'
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      configuration: '$(buildConfiguration)'
      platform: '$(platform)'
