stages:
- stage: Build
  jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: chmod +x utils/premake5 && utils/premake5 gmake
      displayName: 'Generate Makefile'
    - script: cd Build && make -j 3 CXX=g++-7 CC=gcc-7 config=release_x64
      displayName: 'Build project'
    - script: mv $(Build.SourcesDirectory)/Bin/Release/libml_jwt.so $(Build.SourcesDirectory)/Bin/Release/ml_jwt.so
    - publish: '$(Build.SourcesDirectory)/Bin/Release/ml_jwt.so'
      artifact: 'ml_jwt_linux'
  - job: macOS
    pool:
      vmImage: 'macOS-10.14'
    steps:
    - script: brew install gcc
      displayName: Install gcc
    - script: chmod +x utils/premake5-macos && utils/premake5-macos gmake
      displayName: 'Generate Makefile'
    - script: cd Build && make -j 3 CXX=g++-8 CC=gcc-8 config=release_x64
      displayName: 'Build project'
    - script: mv $(Build.SourcesDirectory)/Bin/Release/libml_jwt.so $(Build.SourcesDirectory)/Bin/Release/ml_jwt_darwin.so
    - publish: '$(Build.SourcesDirectory)/Bin/Release/ml_jwt_darwin.so'
      artifact: 'ml_jwt_darwin'
  - job: Windows
    pool:
      vmImage: 'windows-2019'
    strategy:
      maxParallel: 2
      matrix:
        Win32:
          platform: 'win32'
        x64:
          platform: 'x64'
    variables:
      solution: 'Build/JWT.sln'
      buildConfiguration: 'Release'
    steps:
    - script: utils\premake5 vs2019
      displayName: 'Create Visual Studio 2019 Solution'
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        configuration: '$(buildConfiguration)'
        platform: '$(platform)'
    - script: move /Y $(Build.SourcesDirectory)\Bin\Release\ml_jwt.dll $(Build.SourcesDirectory)\Bin\Release\ml_jwt_$(platform).dll
    - publish: '$(Build.SourcesDirectory)\Bin\Release\ml_jwt_$(platform).dll'
      artifact: 'ml_jwt_$(platform)'
